repos:
  # General pre-commit hooks
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json

  # clang-format (C/C++/Objective-C)
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.4
    hooks:
      - id: clang-format
